name: Setup poetry
description: Setup poetry according to .tool-versions

inputs:
  aws-access-key-id:
    description: AWS access key ID
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9.13"
    - name: Install poetry
      run: pip install poetry==1.3.1
      shell: bash
