name: Update renovate PR

on:
  push:
    branches:
      - 'renovate/*'
    paths:
      - 'poetry.lock'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"
      - name: Install poetry
        run: pip install poetry==1.3.1
        shell: bash
      - name: Configure git
        uses: kota65535/github-git-config-action@main
        with:
          user.name: github-actions[bot]
          user.email: 41898282+github-actions[bot]@users.noreply.github.com
      - name: Update requirements.txt
        run: |
          poetry export -o requirements.txt
      - name: Commit & push
        run: |
          git add .
          git commit -m 'update requirements.txt'
          git push origin HEAD
