name: Update renovate PR

on:
  push:
    branches:
      - 'renovate/*'
    paths:
      - 'poetry.lock'
  workflow_dispatch:

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup poetry
        uses: ./.github/actions/setup-poetry
        with:
          working-directory: lambda
      - name: Configure git
        uses: kota65535/github-git-config-action@main
        with:
          user.name: github-actions[bot]
          user.email: 41898282+github-actions[bot]@users.noreply.github.com
      - name: Run pre-commit hook script
        run: |
          poetry export -o requirements.txt
      - name: Commit & push
        run: |
          git add .
          git commit -m 'update requirements.txt'
          git push origin HEAD
